import {
  type LucideIcon,
  Calendar,
  Mail,
  HardDrive,
  MessageSquare,
  Github,
  Users,
  FileText,
  Target,
  Video,
  Hash,
  Send,
  Phone,
  MessageCircle,
  Shield,
  Building2,
  Clock,
  Briefcase,
  PieChart,
  TrendingUp,
  Linkedin,
  Headphones,
  GitBranch,
  AlertTriangle,
  Bug,
  Activity,
  Cloud,
  Rocket,
  Train,
  BookOpen,
  Database,
  FileSpreadsheet,
  CreditCard,
  Receipt,
  DollarSign,
  Wallet,
  UserCheck,
  Search,
  Heart,
  CalendarDays,
  BarChart3,
  Layers,
  LineChart,
  HelpCircle,
  LifeBuoy,
  Megaphone,
  Share2,
  AtSign,
  Lock,
  Key,
  Twitter,
  Zap,
  Box,
  Cpu,
  Globe,
  Radio,
  Mic,
} from "lucide-react";

export type IntegrationCategory =
  | "communication"
  | "email"
  | "crm"
  | "project"
  | "development"
  | "documentation"
  | "finance"
  | "hr"
  | "analytics"
  | "support"
  | "marketing"
  | "security";

export interface IntegrationProvider {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  color: string;
  capabilities: string[];
  scopes: string[];
  docsUrl?: string;
  category: IntegrationCategory;
  comingSoon?: boolean;
}

export const integrationProviders: IntegrationProvider[] = [
  // ============================================
  // COMMUNICATION & MESSAGING
  // ============================================
  {
    id: "slack",
    name: "Slack",
    description: "Send messages, receive notifications, and manage channels",
    icon: MessageSquare,
    color: "#4A154B",
    capabilities: ["Send Messages", "Read Channels", "Notifications", "Files"],
    scopes: [
      "Post messages to channels",
      "Read messages in channels",
      "Access workspace information",
      "Upload and share files",
    ],
    docsUrl: "https://api.slack.com",
    category: "communication",
    comingSoon: false,
  },
  {
    id: "microsoft-teams",
    name: "Microsoft Teams",
    description: "Team chat, channels, meetings, and collaboration",
    icon: Video,
    color: "#6264A7",
    capabilities: ["Chat", "Channels", "Meetings", "Files", "Calls"],
    scopes: [
      "Send and receive messages",
      "Manage team channels",
      "Schedule and join meetings",
      "Access shared files",
    ],
    docsUrl: "https://docs.microsoft.com/en-us/graph/teams-concept-overview",
    category: "communication",
    comingSoon: false,
  },
  {
    id: "discord",
    name: "Discord",
    description: "Server management, bot integration, and community tools",
    icon: Hash,
    color: "#5865F2",
    capabilities: ["Messages", "Servers", "Channels", "Roles", "Webhooks"],
    scopes: [
      "Send messages in channels",
      "Manage server settings",
      "Create and manage roles",
      "Access member information",
    ],
    docsUrl: "https://discord.com/developers/docs",
    category: "communication",
    comingSoon: false,
  },
  {
    id: "telegram",
    name: "Telegram",
    description: "Bot API, channel management, and messaging automation",
    icon: Send,
    color: "#0088CC",
    capabilities: ["Bots", "Channels", "Groups", "Messages", "Media"],
    scopes: [
      "Send and receive messages",
      "Manage channels and groups",
      "Handle inline queries",
      "Process media files",
    ],
    docsUrl: "https://core.telegram.org/bots/api",
    category: "communication",
    comingSoon: false,
  },
  {
    id: "whatsapp",
    name: "WhatsApp Business",
    description: "Business messaging, templates, and customer communication",
    icon: Phone,
    color: "#25D366",
    capabilities: ["Messages", "Templates", "Media", "Contacts", "Catalogs"],
    scopes: [
      "Send business messages",
      "Use message templates",
      "Share media and documents",
      "Manage business profile",
    ],
    docsUrl: "https://developers.facebook.com/docs/whatsapp",
    category: "communication",
    comingSoon: true,
  },
  {
    id: "signal",
    name: "Signal",
    description: "Secure end-to-end encrypted messaging",
    icon: Shield,
    color: "#3A76F0",
    capabilities: ["Secure Messages", "Groups", "Media", "Calls"],
    scopes: [
      "Send encrypted messages",
      "Manage group conversations",
      "Share media securely",
    ],
    docsUrl: "https://signal.org/docs/",
    category: "communication",
    comingSoon: true,
  },
  {
    id: "imessage",
    name: "iMessage",
    description: "Apple Messages integration via bridge",
    icon: MessageCircle,
    color: "#007AFF",
    capabilities: ["Messages", "Group Chats", "Media", "Reactions"],
    scopes: [
      "Send and receive iMessages",
      "Access conversation history",
      "Share media and attachments",
    ],
    docsUrl: "https://developer.apple.com/documentation/messages",
    category: "communication",
    comingSoon: true,
  },
  {
    id: "intercom",
    name: "Intercom",
    description: "Customer messaging platform for support and engagement",
    icon: MessageCircle,
    color: "#1F8EED",
    capabilities: ["Live Chat", "Inbox", "Bots", "Articles", "Campaigns"],
    scopes: [
      "Manage conversations",
      "Access user data",
      "Send targeted messages",
      "Create help articles",
    ],
    docsUrl: "https://developers.intercom.com",
    category: "communication",
    comingSoon: true,
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "SMS, voice, video, and messaging APIs",
    icon: Phone,
    color: "#F22F46",
    capabilities: ["SMS", "Voice", "Video", "WhatsApp", "Email"],
    scopes: [
      "Send SMS messages",
      "Make voice calls",
      "Create video rooms",
      "Access messaging logs",
    ],
    docsUrl: "https://www.twilio.com/docs",
    category: "communication",
    comingSoon: false,
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "AI voice synthesis for natural-sounding calls and audio",
    icon: Mic,
    color: "#000000",
    capabilities: ["Text-to-Speech", "Voice Cloning", "Conversational AI", "Voice Agents"],
    scopes: [
      "Generate speech from text",
      "Create voice agents",
      "Access voice library",
      "Real-time voice synthesis",
    ],
    docsUrl: "https://elevenlabs.io/docs",
    category: "communication",
    comingSoon: false,
  },

  // ============================================
  // EMAIL & CALENDAR
  // ============================================
  {
    id: "google",
    name: "Google Workspace",
    description: "Connect Calendar, Gmail, and Drive for seamless productivity",
    icon: Calendar,
    color: "#4285F4",
    capabilities: ["Calendar Events", "Email", "Drive Files", "Contacts"],
    scopes: [
      "Read and manage your calendar events",
      "Send and read emails on your behalf",
      "Access files in Google Drive",
      "View contact information",
    ],
    docsUrl: "https://developers.google.com/workspace",
    category: "email",
    comingSoon: false,
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    description: "Outlook, Calendar, OneDrive, and Office apps",
    icon: Mail,
    color: "#0078D4",
    capabilities: ["Outlook", "Calendar", "OneDrive", "Teams", "Office"],
    scopes: [
      "Read and send emails",
      "Manage calendar events",
      "Access OneDrive files",
      "View contacts and people",
    ],
    docsUrl: "https://docs.microsoft.com/en-us/graph/",
    category: "email",
    comingSoon: true,
  },
  {
    id: "calendly",
    name: "Calendly",
    description: "Scheduling automation and meeting management",
    icon: Clock,
    color: "#006BFF",
    capabilities: ["Scheduling", "Availability", "Events", "Webhooks"],
    scopes: [
      "Access scheduling links",
      "View and manage events",
      "Set availability",
      "Receive booking notifications",
    ],
    docsUrl: "https://developer.calendly.com",
    category: "email",
    comingSoon: true,
  },
  {
    id: "cal-com",
    name: "Cal.com",
    description: "Open source scheduling infrastructure",
    icon: CalendarDays,
    color: "#292929",
    capabilities: ["Scheduling", "Teams", "Workflows", "API"],
    scopes: [
      "Manage booking types",
      "Access availability",
      "Handle team scheduling",
      "Customize workflows",
    ],
    docsUrl: "https://cal.com/docs",
    category: "email",
    comingSoon: true,
  },

  // ============================================
  // CRM & SALES
  // ============================================
  {
    id: "hubspot",
    name: "HubSpot",
    description: "CRM, marketing, sales, and service platform",
    icon: Users,
    color: "#FF7A59",
    capabilities: ["Contacts", "Deals", "Companies", "Tasks", "Marketing"],
    scopes: [
      "Read and write contact records",
      "Manage deals and pipeline stages",
      "Access company information",
      "Create and update tasks",
    ],
    docsUrl: "https://developers.hubspot.com",
    category: "crm",
    comingSoon: false,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Enterprise CRM and sales cloud platform",
    icon: Cloud,
    color: "#00A1E0",
    capabilities: ["Leads", "Opportunities", "Accounts", "Reports", "Automation"],
    scopes: [
      "Manage leads and contacts",
      "Access opportunities",
      "View account information",
      "Run reports and dashboards",
    ],
    docsUrl: "https://developer.salesforce.com",
    category: "crm",
    comingSoon: false,
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "Sales CRM and pipeline management",
    icon: TrendingUp,
    color: "#017737",
    capabilities: ["Deals", "Contacts", "Pipeline", "Activities", "Goals"],
    scopes: [
      "Manage deals and pipelines",
      "Access contact information",
      "Track activities",
      "View sales insights",
    ],
    docsUrl: "https://developers.pipedrive.com",
    category: "crm",
    comingSoon: true,
  },
  {
    id: "close",
    name: "Close",
    description: "Inside sales CRM for fast-growing teams",
    icon: Phone,
    color: "#333333",
    capabilities: ["Leads", "Calls", "Emails", "SMS", "Pipeline"],
    scopes: [
      "Access lead information",
      "Make and log calls",
      "Send emails and SMS",
      "Track pipeline progress",
    ],
    docsUrl: "https://developer.close.com",
    category: "crm",
    comingSoon: true,
  },
  {
    id: "apollo",
    name: "Apollo",
    description: "Sales intelligence and engagement platform",
    icon: Search,
    color: "#6C5CE7",
    capabilities: ["Prospecting", "Sequences", "Enrichment", "Analytics"],
    scopes: [
      "Search for prospects",
      "Manage email sequences",
      "Enrich contact data",
      "View engagement analytics",
    ],
    docsUrl: "https://apolloio.github.io/apollo-api-docs/",
    category: "crm",
    comingSoon: true,
  },
  {
    id: "linkedin-sales-navigator",
    name: "LinkedIn Sales Navigator",
    description: "B2B prospecting and social selling",
    icon: Linkedin,
    color: "#0A66C2",
    capabilities: ["Lead Search", "InMail", "Insights", "CRM Sync"],
    scopes: [
      "Search for leads and accounts",
      "Send InMail messages",
      "Access sales insights",
      "Sync with CRM",
    ],
    docsUrl: "https://docs.microsoft.com/en-us/linkedin/sales/",
    category: "crm",
    comingSoon: true,
  },
  {
    id: "outreach",
    name: "Outreach",
    description: "Sales engagement and execution platform",
    icon: Megaphone,
    color: "#5951FF",
    capabilities: ["Sequences", "Tasks", "Calls", "Analytics", "AI"],
    scopes: [
      "Manage sales sequences",
      "Track engagement",
      "Log activities",
      "Access AI insights",
    ],
    docsUrl: "https://api.outreach.io/api/v2/docs",
    category: "crm",
    comingSoon: true,
  },
  {
    id: "gong",
    name: "Gong",
    description: "Revenue intelligence platform",
    icon: Headphones,
    color: "#7856FF",
    capabilities: ["Call Recording", "Insights", "Deals", "Coaching"],
    scopes: [
      "Access call recordings",
      "View deal intelligence",
      "Get coaching insights",
      "Analyze conversations",
    ],
    docsUrl: "https://gong.io/api",
    category: "crm",
    comingSoon: true,
  },

  // ============================================
  // PROJECT MANAGEMENT
  // ============================================
  {
    id: "linear",
    name: "Linear",
    description: "Modern issue tracking for high-performance teams",
    icon: Target,
    color: "#5E6AD2",
    capabilities: ["Issues", "Projects", "Cycles", "Teams", "Roadmaps"],
    scopes: [
      "Read and create issues",
      "Access project information",
      "Manage cycle planning",
      "View team structure",
    ],
    docsUrl: "https://developers.linear.app",
    category: "project",
    comingSoon: false,
  },
  {
    id: "jira",
    name: "Jira",
    description: "Enterprise issue tracking and agile project management",
    icon: Zap,
    color: "#0052CC",
    capabilities: ["Issues", "Sprints", "Boards", "Workflows", "Reports"],
    scopes: [
      "Create and manage issues",
      "Access sprint information",
      "View project boards",
      "Generate reports",
    ],
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/",
    category: "project",
    comingSoon: false,
  },
  {
    id: "asana",
    name: "Asana",
    description: "Work management and team collaboration platform",
    icon: Target,
    color: "#F06A6A",
    capabilities: ["Tasks", "Projects", "Timelines", "Goals", "Portfolios"],
    scopes: [
      "Manage tasks and subtasks",
      "Access project timelines",
      "Track team goals",
      "View portfolio status",
    ],
    docsUrl: "https://developers.asana.com",
    category: "project",
    comingSoon: true,
  },
  {
    id: "monday",
    name: "Monday.com",
    description: "Work OS for teams to run processes and projects",
    icon: Layers,
    color: "#FF3D57",
    capabilities: ["Boards", "Items", "Automations", "Dashboards", "Docs"],
    scopes: [
      "Access board data",
      "Create and update items",
      "Manage automations",
      "View dashboards",
    ],
    docsUrl: "https://developer.monday.com",
    category: "project",
    comingSoon: true,
  },
  {
    id: "trello",
    name: "Trello",
    description: "Visual kanban boards for project management",
    icon: Box,
    color: "#0079BF",
    capabilities: ["Boards", "Cards", "Lists", "Labels", "Automations"],
    scopes: [
      "Create and manage boards",
      "Move cards across lists",
      "Add labels and attachments",
      "Set up Power-Ups",
    ],
    docsUrl: "https://developer.atlassian.com/cloud/trello/",
    category: "project",
    comingSoon: true,
  },
  {
    id: "clickup",
    name: "ClickUp",
    description: "All-in-one productivity and project management",
    icon: Target,
    color: "#7B68EE",
    capabilities: ["Tasks", "Docs", "Goals", "Time Tracking", "Dashboards"],
    scopes: [
      "Manage tasks and checklists",
      "Access team docs",
      "Track goals and OKRs",
      "View time reports",
    ],
    docsUrl: "https://clickup.com/api",
    category: "project",
    comingSoon: true,
  },
  {
    id: "basecamp",
    name: "Basecamp",
    description: "Project management and team communication",
    icon: Building2,
    color: "#1D2D35",
    capabilities: ["Projects", "To-dos", "Messages", "Schedules", "Docs"],
    scopes: [
      "Access project campfires",
      "Manage to-do lists",
      "Post messages and updates",
      "View schedules",
    ],
    docsUrl: "https://github.com/basecamp/bc3-api",
    category: "project",
    comingSoon: true,
  },

  // ============================================
  // DEVELOPMENT & DEVOPS
  // ============================================
  {
    id: "github",
    name: "GitHub",
    description: "Code hosting, CI/CD, and developer collaboration",
    icon: Github,
    color: "#24292F",
    capabilities: ["Repositories", "Issues", "Pull Requests", "Actions", "Packages"],
    scopes: [
      "Access repository information",
      "Create and manage issues",
      "Read and comment on pull requests",
      "Trigger workflow actions",
    ],
    docsUrl: "https://docs.github.com/en/rest",
    category: "development",
    comingSoon: false,
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "Complete DevOps platform in a single application",
    icon: GitBranch,
    color: "#FC6D26",
    capabilities: ["Repositories", "CI/CD", "Issues", "Merge Requests", "Registry"],
    scopes: [
      "Access project repositories",
      "Manage CI/CD pipelines",
      "Create merge requests",
      "View container registry",
    ],
    docsUrl: "https://docs.gitlab.com/ee/api/",
    category: "development",
    comingSoon: true,
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    description: "Git code management and CI/CD for teams",
    icon: GitBranch,
    color: "#0052CC",
    capabilities: ["Repositories", "Pipelines", "Pull Requests", "Code Review"],
    scopes: [
      "Access repository data",
      "Manage pipelines",
      "Review pull requests",
      "View build status",
    ],
    docsUrl: "https://developer.atlassian.com/cloud/bitbucket/",
    category: "development",
    comingSoon: true,
  },
  {
    id: "datadog",
    name: "Datadog",
    description: "Monitoring, security, and analytics platform",
    icon: Activity,
    color: "#632CA6",
    capabilities: ["Metrics", "Logs", "APM", "Alerts", "Dashboards"],
    scopes: [
      "Access monitoring metrics",
      "Query logs",
      "View APM traces",
      "Manage alerts",
    ],
    docsUrl: "https://docs.datadoghq.com/api/",
    category: "development",
    comingSoon: false,
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    description: "Incident management and response platform",
    icon: AlertTriangle,
    color: "#06AC38",
    capabilities: ["Incidents", "On-Call", "Alerts", "Escalations", "Analytics"],
    scopes: [
      "Create and manage incidents",
      "View on-call schedules",
      "Configure alert routing",
      "Access incident analytics",
    ],
    docsUrl: "https://developer.pagerduty.com",
    category: "development",
    comingSoon: false,
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Error tracking and performance monitoring",
    icon: Bug,
    color: "#362D59",
    capabilities: ["Errors", "Performance", "Releases", "Alerts", "Issues"],
    scopes: [
      "View error reports",
      "Access performance data",
      "Track releases",
      "Manage issue assignments",
    ],
    docsUrl: "https://docs.sentry.io/api/",
    category: "development",
    comingSoon: false,
  },
  {
    id: "new-relic",
    name: "New Relic",
    description: "Full-stack observability platform",
    icon: LineChart,
    color: "#008C99",
    capabilities: ["APM", "Infrastructure", "Logs", "Synthetics", "Alerts"],
    scopes: [
      "Access APM data",
      "View infrastructure metrics",
      "Query logs",
      "Manage alert policies",
    ],
    docsUrl: "https://docs.newrelic.com/docs/apis/",
    category: "development",
    comingSoon: true,
  },
  {
    id: "aws",
    name: "AWS",
    description: "Amazon Web Services cloud platform",
    icon: Cloud,
    color: "#FF9900",
    capabilities: ["EC2", "S3", "Lambda", "RDS", "CloudWatch"],
    scopes: [
      "Manage EC2 instances",
      "Access S3 buckets",
      "Deploy Lambda functions",
      "Monitor CloudWatch metrics",
    ],
    docsUrl: "https://docs.aws.amazon.com/",
    category: "development",
    comingSoon: true,
  },
  {
    id: "vercel",
    name: "Vercel",
    description: "Frontend deployment and serverless functions",
    icon: Rocket,
    color: "#000000",
    capabilities: ["Deployments", "Domains", "Functions", "Analytics", "Edge"],
    scopes: [
      "Deploy projects",
      "Manage domains",
      "View deployment logs",
      "Access analytics",
    ],
    docsUrl: "https://vercel.com/docs/rest-api",
    category: "development",
    comingSoon: true,
  },
  {
    id: "railway",
    name: "Railway",
    description: "Infrastructure platform for developers",
    icon: Train,
    color: "#0B0D0E",
    capabilities: ["Deployments", "Databases", "Cron Jobs", "Environments"],
    scopes: [
      "Deploy services",
      "Provision databases",
      "Schedule cron jobs",
      "Manage environments",
    ],
    docsUrl: "https://docs.railway.app/reference/public-api",
    category: "development",
    comingSoon: true,
  },

  // ============================================
  // DOCUMENTATION & KNOWLEDGE
  // ============================================
  {
    id: "notion",
    name: "Notion",
    description: "Connected workspace for docs, wikis, and projects",
    icon: FileText,
    color: "#000000",
    capabilities: ["Pages", "Databases", "Blocks", "Comments", "Search"],
    scopes: [
      "Read page content",
      "Query and update databases",
      "Create new pages and blocks",
      "Read and post comments",
    ],
    docsUrl: "https://developers.notion.com",
    category: "documentation",
    comingSoon: false,
  },
  {
    id: "confluence",
    name: "Confluence",
    description: "Enterprise wiki and team collaboration",
    icon: BookOpen,
    color: "#0052CC",
    capabilities: ["Pages", "Spaces", "Templates", "Comments", "Search"],
    scopes: [
      "Create and edit pages",
      "Access space content",
      "Use templates",
      "Search across wiki",
    ],
    docsUrl: "https://developer.atlassian.com/cloud/confluence/",
    category: "documentation",
    comingSoon: true,
  },
  {
    id: "coda",
    name: "Coda",
    description: "Docs that bring together all your team's work",
    icon: FileText,
    color: "#F46A54",
    capabilities: ["Docs", "Tables", "Formulas", "Packs", "Automations"],
    scopes: [
      "Access doc content",
      "Read and write tables",
      "Execute formulas",
      "Use Pack integrations",
    ],
    docsUrl: "https://coda.io/developers/apis/v1",
    category: "documentation",
    comingSoon: true,
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Low-code platform for building apps and databases",
    icon: Database,
    color: "#18BFFF",
    capabilities: ["Bases", "Tables", "Records", "Views", "Automations"],
    scopes: [
      "Access bases and tables",
      "Create and update records",
      "Configure views",
      "Set up automations",
    ],
    docsUrl: "https://airtable.com/developers/web/api/introduction",
    category: "documentation",
    comingSoon: true,
  },
  {
    id: "google-docs",
    name: "Google Docs",
    description: "Collaborative document editing and sharing",
    icon: FileText,
    color: "#4285F4",
    capabilities: ["Documents", "Comments", "Suggestions", "Sharing"],
    scopes: [
      "Read and write documents",
      "Add comments and suggestions",
      "Manage sharing permissions",
      "Export to various formats",
    ],
    docsUrl: "https://developers.google.com/docs/api",
    category: "documentation",
    comingSoon: true,
  },

  // ============================================
  // FINANCE & ACCOUNTING
  // ============================================
  {
    id: "stripe",
    name: "Stripe",
    description: "Payments, billing, and financial infrastructure",
    icon: CreditCard,
    color: "#635BFF",
    capabilities: ["Payments", "Subscriptions", "Invoices", "Customers", "Reports"],
    scopes: [
      "Process payments",
      "Manage subscriptions",
      "Create invoices",
      "Access financial reports",
    ],
    docsUrl: "https://stripe.com/docs/api",
    category: "finance",
    comingSoon: false,
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    description: "Small business accounting and finance",
    icon: Receipt,
    color: "#2CA01C",
    capabilities: ["Invoices", "Expenses", "Reports", "Payroll", "Banking"],
    scopes: [
      "Create and manage invoices",
      "Track expenses",
      "Generate financial reports",
      "Access bank transactions",
    ],
    docsUrl: "https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account",
    category: "finance",
    comingSoon: true,
  },
  {
    id: "xero",
    name: "Xero",
    description: "Cloud-based accounting software",
    icon: DollarSign,
    color: "#13B5EA",
    capabilities: ["Invoicing", "Bills", "Bank Reconciliation", "Reports", "Payroll"],
    scopes: [
      "Create invoices and quotes",
      "Manage bills and payments",
      "Reconcile bank feeds",
      "Access financial reports",
    ],
    docsUrl: "https://developer.xero.com",
    category: "finance",
    comingSoon: true,
  },
  {
    id: "expensify",
    name: "Expensify",
    description: "Expense management and receipt tracking",
    icon: Receipt,
    color: "#1A4D2E",
    capabilities: ["Receipts", "Reports", "Approval", "Cards", "Travel"],
    scopes: [
      "Submit expenses",
      "Scan receipts",
      "Approve reports",
      "Track card transactions",
    ],
    docsUrl: "https://integrations.expensify.com/Integration-Server/doc/",
    category: "finance",
    comingSoon: true,
  },
  {
    id: "bill-com",
    name: "Bill.com",
    description: "AP/AR automation and payment processing",
    icon: Wallet,
    color: "#00A5CA",
    capabilities: ["Accounts Payable", "Accounts Receivable", "Payments", "Approvals"],
    scopes: [
      "Manage bills and invoices",
      "Process payments",
      "Set up approval workflows",
      "Sync with accounting",
    ],
    docsUrl: "https://developer.bill.com/hc/en-us",
    category: "finance",
    comingSoon: true,
  },

  // ============================================
  // HR & RECRUITING
  // ============================================
  {
    id: "greenhouse",
    name: "Greenhouse",
    description: "Applicant tracking and recruiting platform",
    icon: UserCheck,
    color: "#3AB549",
    capabilities: ["Jobs", "Candidates", "Interviews", "Scorecards", "Offers"],
    scopes: [
      "Manage job postings",
      "Track candidates",
      "Schedule interviews",
      "Submit scorecards",
    ],
    docsUrl: "https://developers.greenhouse.io",
    category: "hr",
    comingSoon: true,
  },
  {
    id: "lever",
    name: "Lever",
    description: "Talent acquisition suite for hiring teams",
    icon: Users,
    color: "#2D3D5C",
    capabilities: ["Opportunities", "Candidates", "Feedback", "Offers", "Reports"],
    scopes: [
      "Access candidate profiles",
      "Submit feedback",
      "Manage opportunities",
      "View hiring reports",
    ],
    docsUrl: "https://hire.lever.co/developer/documentation",
    category: "hr",
    comingSoon: true,
  },
  {
    id: "bamboohr",
    name: "BambooHR",
    description: "HR software for people-first companies",
    icon: Heart,
    color: "#73C41D",
    capabilities: ["Employee Data", "Time Off", "Onboarding", "Reports", "Benefits"],
    scopes: [
      "Access employee directory",
      "Manage time off requests",
      "Track onboarding tasks",
      "Generate HR reports",
    ],
    docsUrl: "https://documentation.bamboohr.com/reference",
    category: "hr",
    comingSoon: true,
  },
  {
    id: "workday",
    name: "Workday",
    description: "Enterprise human capital management",
    icon: Briefcase,
    color: "#005CB9",
    capabilities: ["HCM", "Payroll", "Time Tracking", "Benefits", "Analytics"],
    scopes: [
      "Access worker data",
      "Manage time and attendance",
      "Process payroll",
      "View workforce analytics",
    ],
    docsUrl: "https://developer.workday.com",
    category: "hr",
    comingSoon: true,
  },

  // ============================================
  // ANALYTICS & DATA
  // ============================================
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Product analytics for user behavior insights",
    icon: PieChart,
    color: "#7856FF",
    capabilities: ["Events", "Funnels", "Retention", "Cohorts", "A/B Tests"],
    scopes: [
      "Track events",
      "Analyze funnels",
      "View retention data",
      "Create cohorts",
    ],
    docsUrl: "https://developer.mixpanel.com",
    category: "analytics",
    comingSoon: true,
  },
  {
    id: "amplitude",
    name: "Amplitude",
    description: "Digital analytics platform for growth",
    icon: BarChart3,
    color: "#0061FF",
    capabilities: ["Events", "Behavioral Analytics", "Experiments", "CDP"],
    scopes: [
      "Send events",
      "Query analytics data",
      "Run experiments",
      "Access user profiles",
    ],
    docsUrl: "https://www.docs.developers.amplitude.com",
    category: "analytics",
    comingSoon: true,
  },
  {
    id: "segment",
    name: "Segment",
    description: "Customer data platform for unified analytics",
    icon: Layers,
    color: "#52BD95",
    capabilities: ["Sources", "Destinations", "Personas", "Protocols"],
    scopes: [
      "Send event data",
      "Configure destinations",
      "Build user profiles",
      "Define tracking plans",
    ],
    docsUrl: "https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/",
    category: "analytics",
    comingSoon: true,
  },
  {
    id: "google-analytics",
    name: "Google Analytics",
    description: "Web analytics and user behavior tracking",
    icon: LineChart,
    color: "#E37400",
    capabilities: ["Pageviews", "Events", "Conversions", "Audiences", "Reports"],
    scopes: [
      "Access analytics data",
      "View real-time reports",
      "Analyze user journeys",
      "Export custom reports",
    ],
    docsUrl: "https://developers.google.com/analytics",
    category: "analytics",
    comingSoon: true,
  },

  // ============================================
  // CUSTOMER SUPPORT
  // ============================================
  {
    id: "zendesk",
    name: "Zendesk",
    description: "Customer service and support platform",
    icon: LifeBuoy,
    color: "#03363D",
    capabilities: ["Tickets", "Chat", "Knowledge Base", "Reports", "Automations"],
    scopes: [
      "Create and manage tickets",
      "Access customer data",
      "Update knowledge base",
      "View support analytics",
    ],
    docsUrl: "https://developer.zendesk.com",
    category: "support",
    comingSoon: false,
  },
  {
    id: "freshdesk",
    name: "Freshdesk",
    description: "Help desk and customer support software",
    icon: HelpCircle,
    color: "#25C16F",
    capabilities: ["Tickets", "Automations", "Reports", "Knowledge Base", "Chat"],
    scopes: [
      "Manage support tickets",
      "Automate workflows",
      "Access reports",
      "Update help articles",
    ],
    docsUrl: "https://developers.freshdesk.com",
    category: "support",
    comingSoon: true,
  },
  {
    id: "help-scout",
    name: "Help Scout",
    description: "Customer service platform for growing teams",
    icon: LifeBuoy,
    color: "#1292EE",
    capabilities: ["Conversations", "Docs", "Beacon", "Reports", "Workflows"],
    scopes: [
      "Manage conversations",
      "Access customer data",
      "Update documentation",
      "View team reports",
    ],
    docsUrl: "https://developer.helpscout.com",
    category: "support",
    comingSoon: true,
  },

  // ============================================
  // MARKETING & SOCIAL
  // ============================================
  {
    id: "buffer",
    name: "Buffer",
    description: "Social media scheduling and analytics",
    icon: Share2,
    color: "#168DE2",
    capabilities: ["Scheduling", "Analytics", "Engagement", "Start Page"],
    scopes: [
      "Schedule posts",
      "Access analytics",
      "Manage social accounts",
      "View engagement data",
    ],
    docsUrl: "https://buffer.com/developers/api",
    category: "marketing",
    comingSoon: true,
  },
  {
    id: "hootsuite",
    name: "Hootsuite",
    description: "Social media management platform",
    icon: Globe,
    color: "#000000",
    capabilities: ["Publishing", "Monitoring", "Analytics", "Streams"],
    scopes: [
      "Schedule and publish posts",
      "Monitor social mentions",
      "Access analytics reports",
      "Manage streams",
    ],
    docsUrl: "https://developer.hootsuite.com",
    category: "marketing",
    comingSoon: true,
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Email marketing and automation platform",
    icon: Mail,
    color: "#FFE01B",
    capabilities: ["Campaigns", "Audiences", "Automations", "Templates", "Reports"],
    scopes: [
      "Create email campaigns",
      "Manage subscriber lists",
      "Set up automations",
      "View campaign reports",
    ],
    docsUrl: "https://mailchimp.com/developer/",
    category: "marketing",
    comingSoon: true,
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "Email delivery and marketing platform",
    icon: Send,
    color: "#1A82E2",
    capabilities: ["Transactional Email", "Marketing Campaigns", "Templates", "Analytics"],
    scopes: [
      "Send transactional emails",
      "Create marketing campaigns",
      "Manage templates",
      "Access email analytics",
    ],
    docsUrl: "https://docs.sendgrid.com",
    category: "marketing",
    comingSoon: true,
  },
  {
    id: "twitter",
    name: "Twitter / X",
    description: "Social media integration and automation",
    icon: Twitter,
    color: "#000000",
    capabilities: ["Tweets", "DMs", "Mentions", "Analytics", "Lists"],
    scopes: [
      "Post and read tweets",
      "Manage direct messages",
      "Track mentions",
      "Access analytics",
    ],
    docsUrl: "https://developer.twitter.com/en/docs",
    category: "marketing",
    comingSoon: true,
  },

  // ============================================
  // SECURITY
  // ============================================
  {
    id: "snyk",
    name: "Snyk",
    description: "Developer security and vulnerability scanning",
    icon: Shield,
    color: "#4C4A73",
    capabilities: ["Code Scanning", "Dependencies", "Containers", "IaC", "Reports"],
    scopes: [
      "Scan for vulnerabilities",
      "Monitor dependencies",
      "Check container images",
      "View security reports",
    ],
    docsUrl: "https://docs.snyk.io/snyk-api",
    category: "security",
    comingSoon: true,
  },
  {
    id: "1password",
    name: "1Password",
    description: "Password management and secure sharing",
    icon: Key,
    color: "#0094F5",
    capabilities: ["Vaults", "Items", "Secrets", "Events", "Teams"],
    scopes: [
      "Access vault items",
      "Manage secrets",
      "View security events",
      "Administer team access",
    ],
    docsUrl: "https://developer.1password.com",
    category: "security",
    comingSoon: true,
  },
];

export function getProviderById(id: string): IntegrationProvider | undefined {
  return integrationProviders.find((p) => p.id === id);
}

export function getProvidersByCategory(category: IntegrationCategory): IntegrationProvider[] {
  return integrationProviders.filter((p) => p.category === category);
}

export function getAvailableProviders(): IntegrationProvider[] {
  return integrationProviders.filter((p) => !p.comingSoon);
}

export function getComingSoonProviders(): IntegrationProvider[] {
  return integrationProviders.filter((p) => p.comingSoon);
}

// Category metadata for display
export const categoryMeta: Record<IntegrationCategory, { label: string; description: string }> = {
  communication: {
    label: "Communication & Messaging",
    description: "Chat, messaging, and team communication tools",
  },
  email: {
    label: "Email & Calendar",
    description: "Email services, calendars, and scheduling",
  },
  crm: {
    label: "CRM & Sales",
    description: "Customer relationship management and sales tools",
  },
  project: {
    label: "Project Management",
    description: "Issue tracking, tasks, and project planning",
  },
  development: {
    label: "Development & DevOps",
    description: "Code hosting, CI/CD, and developer tools",
  },
  documentation: {
    label: "Documentation & Knowledge",
    description: "Wikis, docs, and knowledge bases",
  },
  finance: {
    label: "Finance & Accounting",
    description: "Payments, invoicing, and financial management",
  },
  hr: {
    label: "HR & Recruiting",
    description: "Human resources and talent acquisition",
  },
  analytics: {
    label: "Analytics & Data",
    description: "Product analytics and data platforms",
  },
  support: {
    label: "Customer Support",
    description: "Help desks and customer service tools",
  },
  marketing: {
    label: "Marketing & Social",
    description: "Social media and marketing automation",
  },
  security: {
    label: "Security",
    description: "Security scanning and access management",
  },
};

// Google sub-services for detailed display
export const googleServices = [
  {
    id: "calendar",
    name: "Google Calendar",
    description: "Manage events and schedules",
    icon: Calendar,
    color: "#4285F4",
  },
  {
    id: "gmail",
    name: "Gmail",
    description: "Read and send emails",
    icon: Mail,
    color: "#EA4335",
  },
  {
    id: "drive",
    name: "Google Drive",
    description: "Access files and documents",
    icon: HardDrive,
    color: "#34A853",
  },
];
